---
# tasks file for mediapeers.instrumental

- name: Add instrumentald apt repo key
  apt_key:
    url: https://packagecloud.io/expectedbehavior/instrumental/gpgkey
    state: present

- name: Add instrumentald apt repo
  apt_repository:
    repo: 'dep https://packagecloud.io/expectedbehavior/instrumental/ubuntu/ {{ ansible_distribution_release }} main'
    state: present
- apt_repository:
    repo: 'dep-src https://packagecloud.io/expectedbehavior/instrumental/ubuntu/ {{ ansible_distribution_release }} main'
    state: present
    update_cache: yes

- name: Install instrumentald apt package
  apt:
    name: instrumentald
    state: present

- name: Add config file instrumentald.toml
  template:
    src: instrumentald.toml.j2
    dest: /etc/instrumentald.toml
  notify: restart instrumentald

- name: Register deamon for startup on boot
  service:
    name: instrumentald
    enabled: yes
