---
# tasks file for mediapeers.instrumental

- name: Add instrumentald repo
  apt_repository:
    # FIXME: use string with dynamic ubuntu code name
    repo: dep https://packagecloud.io/expectedbehavior/instrumental/ubuntu/ trusty main
    state: present

# TODO:
# - add repo key
# - update apt index and install
# - configure
# - restart/activate on boot
